data "azurerm_subscriptions" "subscription" {
  count                 = try(var.subscription.scope_subscription_name, null) != "" ? 1 : 0
  display_name_contains = try(var.subscription.scope_subscription_name, null)
}

resource "azurerm_subscription_policy_assignment" "subscription_assignment" {
  count = try(data.azurerm_subscriptions.subscription[0].subscriptions[0].id, null) != null ? 1 : 0

  name         = try(var.subscription.name, null)
  display_name = try(var.subscription.display_name, null)
  description  = try(var.subscription.description, null)
  enforce      = try(var.subscription.enforce, true)

  location = try(var.subscription.location, null)

  subscription_id      = try(data.azurerm_subscriptions.subscription[0].subscriptions[0].id, null)
  policy_definition_id = try(var.scope, null)
  not_scopes           = try(var.subscription.not_scopes, null)

  dynamic "non_compliance_message" {
    for_each = { for k, v in merge(
      { for k, v in var.policy_definition_reference : k => {
        non_compliance_message = try(v.non_compliance_message, "(Autogenerated) This policy is not compliant!")
        reference_id           = try(v.reference_id, "reference_id_${k}")
        }
      },
      {
        general_non_compliance_message = {
          non_compliance_message = try(var.subscription.non_compliance_message, "(Autogenerated) This policy is not compliant!")
        }
      }
    ) : k => v }

    content {
      content                        = try(non_compliance_message.value.non_compliance_message, null)
      policy_definition_reference_id = try(non_compliance_message.value.reference_id, null)
    }
  }

  identity {
    type         = try(var.subscription.provided_ids, null) != null ? "UserAssigned" : "SystemAssigned"
    identity_ids = try(var.subscription.provided_ids, null)
  }

  metadata   = jsonencode(try(var.subscription.metadata, null))
  parameters = jsonencode(try(var.subscription.parameters, null))
}
