data "azurerm_resource_group" "resource_group" {
  count = try(var.resource_group.scope_resource_group_name, null) != null ? 1 : 0
  name  = try(var.resource_group.scope_resource_group_name, null)
}

resource "azurerm_resource_group_policy_assignment" "resource_group_assignment" {
  count = try(data.azurerm_resource_group.resource_group[0].id, null) != null ? 1 : 0

  name         = try(var.resource_group.name, null)
  display_name = try(var.resource_group.display_name, null)
  description  = try(var.resource_group.description, null)
  enforce      = try(var.resource_group.enforce, true)

  location = try(var.resource_group.location, null)

  resource_group_id    = try(data.azurerm_resource_group.resource_group[0].id, null)
  policy_definition_id = try(var.scope, null)
  not_scopes           = try(var.resource_group.not_scopes, null)

  dynamic "non_compliance_message" {
    for_each = { for k, v in merge(
      { for k, v in var.policy_definition_reference : k => {
        non_compliance_message = try(v.non_compliance_message, "(Autogenerated) This policy is not compliant!")
        reference_id           = try(v.reference_id, "reference_id_${k}")
        }
      },
      {
        general_non_compliance_message = {
          non_compliance_message = try(var.resource_group.non_compliance_message, "(Autogenerated) This policy is not compliant!")
        }
      }
    ) : k => v }

    content {
      content                        = try(non_compliance_message.value.non_compliance_message, null)
      policy_definition_reference_id = try(non_compliance_message.value.reference_id, null)
    }
  }

  identity {
    type         = try(var.resource_group.provided_ids, null) != null ? "UserAssigned" : "SystemAssigned"
    identity_ids = try(var.resource_group.provided_ids, null)
  }

  metadata   = jsonencode(try(var.resource_group.metadata, null))
  parameters = jsonencode(try(var.resource_group.parameters, null))
}
