data "azurerm_resources" "resource" {
  count = try(var.resource.scope_resource_name, null) != null ? 1 : 0
  name  = try(var.resource.scope_resource_name, null)
}

resource "azurerm_resource_policy_assignment" "resource_assignment" {
  count = try(data.azurerm_resources.resource[0].resources[0].id, null) != null ? 1 : 0

  name         = try(var.resource.name, null)
  display_name = try(var.resource.display_name, null)
  description  = try(var.resource.description, null)
  enforce      = try(var.resource.enforce, true)

  location = try(var.resource.location, null)

  resource_id          = try(data.azurerm_resources.resource[0].resources[0].id, null)
  policy_definition_id = try(var.scope, null)
  not_scopes           = try(var.resource.not_scopes, null)

  dynamic "non_compliance_message" {
    for_each = { for k, v in merge(
      { for k, v in var.policy_definition_reference : k => {
        non_compliance_message = try(v.non_compliance_message, "(Autogenerated) This policy is not compliant!")
        reference_id           = try(v.reference_id, "reference_id_${k}")
        }
      },
      {
        general_non_compliance_message = {
          non_compliance_message = try(var.resource.non_compliance_message, "(Autogenerated) This policy is not compliant!")
        }
      }
    ) : k => v }

    content {
      content                        = try(non_compliance_message.value.non_compliance_message, null)
      policy_definition_reference_id = try(non_compliance_message.value.reference_id, null)
    }
  }

  identity {
    type         = try(var.resource.provided_ids, null) != null ? "UserAssigned" : "SystemAssigned"
    identity_ids = try(var.resource.provided_ids, null)
  }

  metadata   = jsonencode(try(var.resource.metadata, null))
  parameters = jsonencode(try(var.resource.parameters, null))
}
